baseURL = "https://davila.io/"
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title = "Jonathan Davila"
theme = ["sam"]
googleAnalytics = "UA-131788790-1"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle           = "dracula"
publishDir = "docs"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "davila.ico"
    homepage            = "Home"
    footerText          = "© Jonathan I. Davila"
    description         = "Who is Jonathan Davila?"

[[params.mainMenu]]
    link = "/about"
    text = "About"

[[params.mainMenu]]
    link = "/posts"
    text = "Blog"

[[params.mainMenu]]
    link = "/projects"
    text = "Projects"

[[params.mainMenu]]
    link = "/contact"
    text = "Contact"
