baseurl = "https://davila.io"
title = "Jonathan I. Davila"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]
publishDir = "../"

[params]
  description = 'Open Source Enthusiast<br>Web, Infrastructure, & Automation Engineer<br>Snowboarder. Veteran. Father.'
  logoimage = "/logo.png"
  copyright = "Jonathan I. Davila"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/defionscode"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/davilaio/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/defionscode"

[[params.social]]
  medium = "keybase"
  icon = "comment-o"
  link = "https://keybase.io/defionscode"

[languages]
[languages.en]
languageName = "English"
weight = 1
